### ISSUE TITLE
How to run the file

### ISSUE THREAD

**Issue by lorenzoromani1983** [mdredze/twitter_stream_downloader#2]
Hi.

Tnx for the script.
I am trying to run it but I am having troubles:

Please help me check if i have made things right!

a) I pasted the access/consumer tokens in rows 78-81

Where do I  have to type the keywords/hashtags I need to stream on Twitter?

I have been trying to run the file WITHOUT typing any keyword, and I get this:

File "C:\Users\Lorenzo\Desktop\Tool\twitter_stream_downloader-master\python\streaming_downloader.py", line 95
    print usage(sys.argv, command_line, options)

Thanks in advance :)

**Comment by mdredze** [comment]
You don't need to paste tokens. These are given on the command line.

If you want to use a keywords crawl, supply these arguments:
-- stream_filename X --stream_type keyword

where X is the filename containing your keywords. I believe the format is:
track=keyword1,keyword2,...

**Comment by lorenzoromani1983** [comment]
I made it! Thank you!

**Comment by lorenzoromani1983** [comment]
Sorry for bothering, but there are some issues going on. 
The streaming is fine, the script is great as it does not hang as other scripts do.
But the problem lies within the Json file it dumps: it is not possible to parse it as all the JSON to csv converters on the market fail when trying to decode such a Json.
The reason is that each tweet is an object and needs to be separated from the next tweet by coma ".". Plus, the file should begin with something like {"tweets": [{created_at.....etc etc etc   and should finish with......   "timestamp_ms":"1489749110528"}]} after hundreds of tweets!.
The reason is that only this way, as far as I know, parsers are able to read the whole dump as one single JSON, otherwise they read each tweet as a single json file and parsing such a twitter streaming dump is not possible.
I guess maybe there is a way to integrate the python script in order to fix this format issue?

thanks, 

Lorenzo

**Comment by mdredze** [comment]
This Python code should read the file:

```import gzip, json
with gzip.open(filename) as input:
    for line in input:
        if len(line.strip()) == 0:
            continue
        tweet = json.loads(line)
        # Do something with the tweet.
```
